runtime: python38
entrypoint: uvicorn app:app --host 0.0.0.0 --port $PORT

env_variables:
  MONGODB_URL: "your-mongodb-url"
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  AWS_DEFAULT_REGION: "us-east-1"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto 