steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/us-visa-app:$COMMIT_SHA', '-f', 'Dockerfile.gcp', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/us-visa-app:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'us-visa-prediction'
      - '--image'
      - 'gcr.io/$PROJECT_ID/us-visa-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'MONGODB_URL=${_MONGODB_URL},GCP_PROJECT_ID=${_GCP_PROJECT_ID}'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/us-visa-app:$COMMIT_SHA'

# Substitution variables
substitutions:
  _MONGODB_URL: 'your-mongodb-url'
  _GCP_PROJECT_ID: 'your-gcp-project-id' 